In [1]:
import pandas as pd
train_df=pd.read_csv("train.csv")
test_df=pd.read_csv('test.csv')

In [2]:
train_df

,seqn,Age,Sex,Marital,Income,Race,WaistCirc,BMI,Albuminuria,UrAlbCr,UricAcid,BloodGlucose,HDL,Triglycerides,MetabolicSyndrome
0,65625,23,Male,Single,800.0,Asian,126.0,38.4,0,7.75,5.0,243,44,205,1
1,65006,47,Female,Separated,8200.0,Black,97.3,29.4,0,3.85,5.2,98,50,104,0
2,68859,39,Female,Married,8200.0,White,98.0,27.9,0,5.06,5.3,92,81,75,0
3,69363,22,Female,Single,1000.0,MexAmerican,113.6,36.5,0,20.42,4.2,97,44,89,0
4,66214,70,Female,Married,3500.0,White,NaN,16.2,1,90.38,4.8,111,55,196,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915,66721,47,Female,Married,9000.0,Asian,NaN,NaN,0,6.92,3.8,86,46,108,0
1916,68594,80,Male,Widowed,1000.0,White,103.2,25.4,0,10.77,5.7,95,39,123,1
1917,63439,51,Male,Married,6200.0,Hispanic,114.6,32.3,2,589.61,6.5,85,49,151,0
1918,69347,49,Male,Married,2500.0,White,110.8,30.1,0,11.27,6.9,112,31,309,1
1919,70231,37,Female,Married,9000.0,Asian,100.5,31.8,0,7.18,3.8,95,32,170,1

In [3]:
print(train_df.shape)
display(train_df.info())
train_df.isnull().sum()

(1920, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920 entries, 0 to 1919
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   seqn               1920 non-null   int64
 1   Age                1920 non-null   int64
 2   Sex                1920 non-null   object
 3   Marital            1755 non-null   object
 4   Income             1825 non-null   float64
 5   Race               1920 non-null   object
 6   WaistCirc          1855 non-null   float64
 7   BMI                1897 non-null   float64
 8   Albuminuria        1920 non-null   int64
 9   UrAlbCr            1920 non-null   float64
 10  UricAcid           1920 non-null   float64
 11  BloodGlucose       1920 non-null   int64
 12  HDL                1920 non-null   int64
 13  Triglycerides      1920 non-null   int64
 14  MetabolicSyndrome  1920 non-null   int64
dtypes: float64(5), int64(7), object(3)
memory usage: 225.1+ KB

None

seqn                   0
Age                    0
Sex                    0
Marital              165
Income                95
Race                   0
WaistCirc             65
BMI                   23
Albuminuria            0
UrAlbCr                0
UricAcid               0
BloodGlucose           0
HDL                    0
Triglycerides          0
MetabolicSyndrome      0
dtype: int64

In [17]:
def info(df):
    inf=pd.DataFrame({
        'dtype':df.dtypes.astype(str),
        'NaN':df.isna().sum(),
        'missing %':(df.isna().mean()*100).round(2),
        'unique':df.nunique()
    })
    return inf

In [18]:
info(train_df)

                     dtype  NaN  missing %  unique
seqn                 int64    0       0.00    1920
Age                  int64    0       0.00      61
Sex                 object    0       0.00       2
Marital             object  165       8.59       5
Income             float64   95       4.95      14
Race                object    0       0.00       6
WaistCirc          float64   65       3.39     609
BMI                float64   23       1.20     306
Albuminuria          int64    0       0.00       3
UrAlbCr            float64    0       0.00    1189
UricAcid           float64    0       0.00      85
BloodGlucose         int64    0       0.00     168
HDL                  int64    0       0.00      87
Triglycerides        int64    0       0.00     323
MetabolicSyndrome    int64    0       0.00       2

In [19]:
info(test_df)

                 dtype  NaN  missing %  unique
id               int64    0       0.00     481
seqn             int64    0       0.00     481
Age              int64    0       0.00      61
Sex             object    0       0.00       2
Marital         object   43       8.94       5
Income         float64   22       4.57      14
Race            object    0       0.00       6
WaistCirc      float64   20       4.16     289
BMI            float64    3       0.62     206
Albuminuria      int64    0       0.00       3
UrAlbCr        float64    0       0.00     426
UricAcid       float64    0       0.00      71
BloodGlucose     int64    0       0.00     102
HDL              int64    0       0.00      76
Triglycerides    int64    0       0.00     201